name: My First Action

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: git clone https://github.com/tumsrichomson/learn-github-actions.git

      - name: Show message
        run: echo "Hello, GitHub Actions!"

      - name: Show files
        run: ls -la
